<?php

namespace ContainerFW1uI3M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Ux_TwigComponent_Twig_ComponentRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux.twig_component.twig.component_runtime' shared service.
     *
     * @return \Symfony\UX\TwigComponent\Twig\ComponentRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/Twig/ComponentRuntime.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentRendererInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentStack.php';

        $a = ($container->privates['twig'] ?? $container->getTwigService());

        if (isset($container->privates['.ux.twig_component.twig.component_runtime'])) {
            return $container->privates['.ux.twig_component.twig.component_runtime'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['.ux.twig_component.twig.component_runtime'])) {
            return $container->privates['.ux.twig_component.twig.component_runtime'];
        }
        $c = ($container->privates['ux.twig_component.component_factory'] ?? $container->load('getUx_TwigComponent_ComponentFactoryService'));

        if (isset($container->privates['.ux.twig_component.twig.component_runtime'])) {
            return $container->privates['.ux.twig_component.twig.component_runtime'];
        }

        return $container->privates['.ux.twig_component.twig.component_runtime'] = new \Symfony\UX\TwigComponent\Twig\ComponentRuntime(new \Symfony\UX\TwigComponent\ComponentRenderer($a, $b, $c, ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), new \Symfony\UX\TwigComponent\ComponentStack()), ($container->privates['.service_locator.Xbsa8iG'] ?? ($container->privates['.service_locator.Xbsa8iG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [], []))));
    }
}
