<?php

namespace ContainerFW1uI3M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteUserCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DeleteUserCommand' shared autowired service.
     *
     * @return \App\Command\DeleteUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DeleteUserCommand.php';

        $container->privates['App\\Command\\DeleteUserCommand'] = $instance = new \App\Command\DeleteUserCommand();

        $instance->setName('app:delete-user');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
