controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_posts:
    path: /api/posts
    controller: App\Controller\ApiController::getPosts
    methods: GET

api_comments:
    path: /api/comments
    controller: App\Controller\ApiController::getComments
    methods: GET

api_users:
    path: /api/users
    controller: App\Controller\ApiController::getUsers
    methods: GET