<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOep4hDE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOep4hDE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOep4hDE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOep4hDE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOep4hDE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oep4hDE',
    'container.build_id' => '25a90db2',
    'container.build_time' => 1732615857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOep4hDE');
