<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFW1uI3M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFW1uI3M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFW1uI3M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFW1uI3M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFW1uI3M\App_KernelDevDebugContainer([
    'container.build_hash' => 'FW1uI3M',
    'container.build_id' => 'ec59774e',
    'container.build_time' => 1732612407,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFW1uI3M');
